import Navbar from '@/components/NavbarComponents/navbarComponents'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './layout.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section style={{position : "fixed" ,width : "100%"}}>
          <Navbar />
        </section>
        <article style={{display : "flex" , alignContent : "center" , justifyContent : "center"  , marginTop : "105px"}}> 
          <section className='container'> 
            {children}
          </section>
        </article>
      </body>
    </html>
  )
}
