import Navbar from '@/components/NavbarComponents/navbarComponents';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './layout.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0, position: 'relative' }}>
        <section
          style={{
            position: 'fixed',
            width: '140px', 
            height: '100vh', 
            top: 0, 
            left: 0, 
            backgroundColor: '#15172b', 
          }}
        >
          <Navbar />
        </section>
        <article style={{ marginLeft: '10%', width: '90%', padding: '20px' }}>
          <section
            className='container'
          >
            {children}
          </section>
        </article>
      </body>
    </html>
  );
}
